### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by jvence** [xxsnakerxx/cordova-plugin-social-auth#1]
I've installed the plugin but I can't seem to access it as socialAuth is an undefined variable. Do I need to initialize it?

**Comment by xxsnakerxx** [comment]
I've found an error in docs, you should access to the plugin instance via cordova.plugins.socialAuth

**Comment by xxsnakerxx** [comment]
@jvence I've updated the docs https://github.com/xxsnakerxx/cordova-plugin-social-auth/commit/8c08dd35b72381ac820a883c21750ba7ea4c0e22

**Comment by xxsnakerxx** [comment]
Closed due no lack activity
